<?php

/**
 * Implementation of hook_form_FORM_ID_alter()
 */
function custom_api_key_form_system_site_information_settings_alter(&$form, &$form_state, $form_id) {
	$form['actions']['submit']['#value'] = t("Update Configuration");
	$form['siteapikey'] = array(
		'#title' => t('Site API Key'),
		'#type' => 'textfield',
		'#default_value' => variable_get('siteapikey', "No API Key yet"),
	);
	$form['#submit'][] = 'site_form_alter_submit';
}

/**
* Custom Submit function.
*/
function  site_form_alter_submit($form, &$form_state) {
    if (isset($form_state['values']['siteapikey'])){
	  $saved_value = variable_set('siteapikey', $form_state['values']['siteapikey']);
      drupal_set_message(t('Site API Key has been saved with "' . $form_state['values']['siteapikey'] . '"'));
    }   
}

/**
 * Implementation of hook_menu()
 */
function custom_api_key_menu() {
  $items['page_json/%/%'] = array(
    'title' => 'Json Code',
    'page callback' => 'custom_services',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

/**
* Custom callback function.
*/
function custom_services() {
	$node = node_load(arg(2));
	if (arg(1) == variable_get('siteapikey') && $node->type == 'page') {
		if (isset($node)) {
			drupal_json_output($node);
            drupal_exit();
		}
		else {
		    drupal_access_denied();
		    drupal_exit();
		}
	}
	else
	{
		drupal_access_denied();
		drupal_exit();
	}
}